### ISSUE TITLE
Possibility of having shared and exclusive collections on server B?

### ISSUE THREAD

**Issue by a4xrbj1** [iamlasse/meteor-ddp-test#1]
Hi Lasse,

first of all thanks for this great package, it's exactly what I'm looking for (I need to share only some collections between server A and B. I have the question, is it possible to have shared and exclusive collections on server B?

Like I want to share the meteor.user collection between server A and B (just have to replace item with users in your source code I guess) but also want to have a couple of collections on my job queue server B (so they need to run on server B's own MongoDB instance).

Is that possible and what do I need to watch out for? Or is it just normal create a new Mongo collection on server B?

**Comment by iamlasse** [comment]
Hi that should be entirely possible since they are in essence mutually exclusive apps that connect over ddp. Apologies for the late late response i just put this out there for sharing but didnt expect feedback lol. Hope you found a solution and please. Share your findings :)
